services:
  - type: web
    name: duosecur-pro
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENV
        value: production
